
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/unit_test?createDatabaseIfNotExist=true
    username: root
    password: admin


